# Generated by Django 5.0.6 on 2026-03-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobroleskill',
            unique_together={('job_role', 'skill')},
        ),
    ]
