# Generated by Django 5.0.6 on 2026-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_jobroleskill_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
